site_name: "Tinyscript - A library for quickly prototyping CLI Python-based tools"
repo_url: https://github.com/dhondta/tinyscript
site_author: dhondta
docs_dir: docs
nav:
  - Introduction: index.md
  - Setup: setup.md
  - Internals: internals.md
  - Features: features.md
  - Helpers: helpers.md
  - Usage: usage.md
  - Examples:
    - 'Simple script': examples/simple-script.md
    - 'Simple tool': examples/simple-tool.md
    - 'Metadata': examples/metadata.md
    - 'Privilege escalation': examples/sudo.md
    - 'Multi-level debugging': examples/multi-level-debug.md
    - 'Multi-level help': examples/multi-level-help.md
    - 'Playing a demo': examples/demo.md
  - 'Real-life examples':
    - 'AppmemDumper': examples-rl/appmemdumper.md
    - 'Bots Scheduler': examples-rl/bots-scheduler.md
    - 'Malicious Macro Tester': examples-rl/malicious-macro-tester.md
    - 'Recursive Compression': examples-rl/recursive-compression.md
    - 'Solitaire Cipher': examples-rl/solitaire-cipher.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
extra_javascript:
  - js/collapsible-navbar.js
use_directory_urls: false
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.details
