site_author: dhondta
site_name: "Tinyscript - Devkit for quickly building CLI tools with Python"
repo_url: https://github.com/dhondta/python-tinyscript
copyright: Copyright &copy; 2017-2023 Alexandre D'Hondt
docs_dir: pages
nav:
  - Introduction: index.md
  - Internals: internals.md
  - 'Enhanced modules': enhancements.md
  - 'Tool shaping': shaping.md
  - 'Report generation': reporting.md
  - 'Utility features': utility.md
  - Helpers: helpers.md
  - Usage: usage.md
  - 'Scripts management': tsm.md
  - Examples:
    - 'Simple script': examples/simple-script.md
    - 'Simple tool': examples/simple-tool.md
    - 'Metadata': examples/metadata.md
    - 'Privilege elevation': examples/sudo.md
    - 'Multi-level debugging': examples/multi-level-debug.md
    - 'Multi-level help': examples/multi-level-help.md
    - 'Playing a demo': examples/demo.md
    - 'Stepping execution': examples/step.md
    - 'Timing execution': examples/timing.md
    - 'Hotkeys': hotkeys/examples.md
  - 'Real-life examples':
    - 'AppmemDumper': examples-rl/appmemdumper.md
    - 'Bots Scheduler': examples-rl/bots-scheduler.md
    - 'Malicious Macro Tester': examples-rl/malicious-macro-tester.md
    - 'Recursive Compression': examples-rl/recursive-compression.md
    - 'Solitaire Cipher': examples-rl/solitaire-cipher.md
extra_css:
  - css/extra.css
extra:
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:alexandre.dhondt@gmail.com
      name: Contact Alex
    - icon: fontawesome/brands/github
      link: https://github.com/dhondta
      name: Alex on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alexandre-d-2ab2aa14/
      name: Alex on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/alex_dhondt
      name: Alex on Twitter
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: img/logo.png
  favicon: img/icon.png
use_directory_urls: false
markdown_extensions:
  - toc:
      permalink: true
  - admonition
